const productList = [
  {
    id: 1,
    name: "Wooden Shape Sorter",
    quantity: 25,
    colours: ["natural wood", "pastel blue", "pastel pink"],
    pricePerUnit: "$24.99",
    favourited: false,
    image: "https://placehold.co/300x300",
  },
  {
    id: 2,
    name: "Montessori Stacking Rings",
    quantity: 40,
    colours: ["rainbow", "neutral"],
    pricePerUnit: "$19.5",
    favourited: true,
    image: "https://placehold.co/300x300",
  },
  {
    id: 3,
    name: "Wooden Number Puzzle",
    quantity: 30,
    colours: ["natural wood", "multicolor"],
    pricePerUnit: "$17.99",
    favourited: false,
    image: "https://placehold.co/300x300",
  },
  {
    id: 4,
    name: "Montessori Sensory Board",
    quantity: 15,
    colours: ["natural wood"],
    pricePerUnit: "$34.99",
    favourited: true,
    image: "https://placehold.co/300x300",
  },
  {
    id: 5,
    name: "Wooden Pull-Along Animal Toy",
    quantity: 20,
    colours: ["yellow", "green", "red"],
    pricePerUnit: "$22.0",
    favourited: false,
    image: "https://placehold.co/300x300",
  },
  {
    id: 6,
    name: "Montessori Color Matching Game",
    quantity: 35,
    colours: ["red", "blue", "green", "yellow"],
    pricePerUnit: "$16.49",
    favourited: false,
    image: "https://placehold.co/300x300",
  },
];

export default productList;
